export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_USER = 'ADD_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const ACTIVE_USERS_LOADED = 'ACTIVE_USERS_LOADED';
export const MESSAGES_LOADED = 'MESSAGES_LOADED';